// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ynfbfabqtqfpxlseyzta.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InluZmJmYWJxdHFmcHhsc2V5enRhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc2MjA3NDIsImV4cCI6MjA3MzE5Njc0Mn0.tFK8TeVvvLduitRpUMwHbnP1nDsCzzlOJPbEIKYKKtE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});